# golangci-lint configuration
# https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Default enabled linters: errcheck, govet, ineffassign, staticcheck, unused
  enable:
    # Additional recommended linters
    - gocritic      # Opinionated Go linter
    - misspell      # Check for misspelled English words
    - gocyclo       # Check cyclomatic complexity
    - gosec         # Security-focused linter

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Reorders fields for memory optimization but removes inline comments

    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - unnamedResult
        - hugeParam

  exclusions:
    rules:
      # Exclude some linters from running on tests
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec

      # Exclude generated code
      - path: \.gen\.go
        linters:
          - all

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  fix: true
