name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: deno task bundle

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bin/*
          token: ${{ secrets.RELEASE_PAT }}
