name: Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: bennypowers/go-release-workflows/.github/workflows/build-binaries.yml@main
    with:
      binary-name: design-tokens-language-server
