name: Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno task test
      - run: deno task build:ci

      - uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_PAT }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          files: |
            dist/bin/*
            extensions/vscode/*.vsix
