name: Test and Build
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test
        run: |
          deno test -A --coverage
          deno coverage --exclude="test/.*.ts\$" --lcov --out=coverage/lcov.info

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          # minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Build step
        run: deno task bundle

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/bin/*
          token: ${{ secrets.RELEASE_PAT }}
