name: Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test
        run: |
          deno test -A --coverage
          deno coverage --exclude="test/.*.ts\$|textDocument\.ts\$" --lcov --output=coverage/lcov.info

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_PAT }}

      - name: Build
        run: deno task build:ci

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          files: |
            dist/bin/*
            extensions/vscode/*.vsix
