name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build Binaries
    uses: bennypowers/go-release-workflows/.github/workflows/build-binaries.yml@main
    with:
      binary-name: design-tokens-language-server
      release-tag: ${{ github.event.release.tag_name }}
